/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelOportunidadVenta',
        'modelCodigoGerenteRegional',
        'modelCodigoVendedor',
        'modelCodigoConsecionario',
        'modelTipoSolicitante',
        'modelTipoEmpresa',
        'modelMarca',
        'modelModelo',
        'modelSolicitudPais',
        'modelSolicitudEstado',
        'modelSolicitudMunicipio',
        'modelSolicitudCiudad'
    ],
    stores: [
        'storeOportunidadVenta',
        'storeCodigoGerenteRegional',
        'storeCodigoVendedor',
        'storeCodigoConsecionario',
        'storeTipoSolicitante',
        'storeTipoEmpresa',
        'storeMarca',
        'storeModelo',
        'storePais',
        'storeEstado',
        'storeCiudad',
        'storeMunicipio'
    ],
    views: [
        'formAplicacion',
        'winOportunidadVenta'
    ],
    name: 'hwtProOportunidadVenta',

    launch: function() {
        Ext.create('hwtProOportunidadVenta.view.formAplicacion', {renderTo: Ext.getBody()});
        elf.defaultDataApp();
    }

});
