/*
 * File: app/view/winParametrosBusqueda.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtCatCliente.view.winParametrosBusqueda', {
    extend: 'Ext.window.Window',
    alias: 'widget.winParametrosBusqueda',

    requires: [
        'hwtCatCliente.view.winParametrosBusquedaViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'winparametrosbusqueda'
    },
    modal: true,
    id: 'winParametrosBusqueda',
    itemId: 'winParametrosBusqueda',
    width: 500,
    closable: false,
    title: 'Búsqueda de Clientes',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            baseCls: 'formBackground',
            id: 'formParametrosBusqueda',
            itemId: 'formParametrosBusqueda',
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetParametrosBusqueda',
                    itemId: 'fieldsetParametrosBusqueda',
                    layout: 'column',
                    title: '<b>Parámetros de Búsqueda</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.7,
                            id: 'fiParamCodigo',
                            itemId: 'fiParamCodigo',
                            margin: '0 5 5 0',
                            fieldLabel: 'Código',
                            enableKeyEvents: true,
                            maskRe: /[0-9.-]/,
                            listeners: {
                                keydown: 'onFiParamCodigoKeydown'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.7,
                            id: 'fiParamNombreCorto',
                            itemId: 'fiParamNombreCorto',
                            margin: '0 5 5 0',
                            fieldLabel: 'Nombre Corto',
                            enableKeyEvents: true,
                            listeners: {
                                keydown: 'onFiParamNombreCortoKeydown'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            id: 'fiParamRazonSocial',
                            itemId: 'fiParamRazonSocial',
                            margin: '0 5 5 0',
                            fieldLabel: 'Razón Social',
                            enableKeyEvents: true,
                            listeners: {
                                keydown: 'onFiParamRazonSocialKeydown'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            id: 'fiParamRFC',
                            itemId: 'fiParamRFC',
                            margin: '0 5 5 0',
                            fieldLabel: 'RFC',
                            enableKeyEvents: true,
                            listeners: {
                                keydown: 'onFiParamRFCKeydown'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            cls: 'toolbarBackground',
            dock: 'bottom',
            id: 'toolbarBusquedaClientes',
            itemId: 'toolbarBusquedaClientes',
            items: [
                {
                    xtype: 'button',
                    id: 'btnEjecutaBusqueda',
                    itemId: 'btnEjecutaBusqueda',
                    width: 135,
                    iconCls: 'fa fa-search icon16 iconColorGreen',
                    text: 'Buscar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnEjecutaBusquedaClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnLimpiarBusqueda',
                    itemId: 'btnLimpiarBusqueda',
                    width: 135,
                    iconCls: 'fa fa-refresh icon16 iconColorDarkBlue',
                    text: 'Limpiar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnLimpiarBusquedaClick'
                    }
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnCierraBusqueda',
                    itemId: 'btnCierraBusqueda',
                    width: 135,
                    iconCls: 'fa fa-window-close icon16 iconColorRed',
                    text: 'Cerrar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnCierraBusquedaClick'
                    }
                }
            ]
        }
    ],

    onFiParamCodigoKeydown: function(textfield, e, eOpts) {
        if(e.getCharCode() == Ext.EventObject.ENTER){
            elf.refreshGrid('gridCliente');
        }
    },

    onFiParamNombreCortoKeydown: function(textfield, e, eOpts) {
        if(e.getCharCode() == Ext.EventObject.ENTER){
            elf.refreshGrid('gridCliente');
        }
    },

    onFiParamRazonSocialKeydown: function(textfield, e, eOpts) {
        if(e.getCharCode() == Ext.EventObject.ENTER){
            elf.refreshGrid('gridCliente');
        }
    },

    onFiParamRFCKeydown: function(textfield, e, eOpts) {
        if(e.getCharCode() == Ext.EventObject.ENTER){
            elf.refreshGrid('gridCliente');
        }
    },

    onBtnEjecutaBusquedaClick: function(button, e, eOpts) {
        elf.refreshGrid('gridCliente');
    },

    onBtnLimpiarBusquedaClick: function(button, e, eOpts) {
        elf.writeElement('fiParamCodigo','');
        elf.writeElement('fiParamNombreCorto','');
        elf.writeElement('fiParamRazonSocial','');
        elf.writeElement('fiParamRFC','');

        elf.refreshGrid('gridCliente');
    },

    onBtnCierraBusquedaClick: function(button, e, eOpts) {
        elf.closeWindow('winParametrosBusqueda');
    }

});