/*
 * File: app/store/storeUnidadUsada.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProUnidades.store.storeUnidadUsada', {
    extend: 'Ext.data.Store',

    requires: [
        'hwtProUnidades.model.modUnidadUsada',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 100,
            storeId: 'storeUnidadUsada',
            model: 'hwtProUnidades.model.modUnidadUsada',
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json',
                    rootProperty: function(data) {
                        var storeUnidadUsada = Ext.getStore('storeUnidadUsada');
                        var rawData = storeUnidadUsada.getProxy().getReader().rawData;
                        return rawData.hwtUnidadUsada;
                    }
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        var storeUnidadUsada = Ext.getStore('storeUnidadUsada');
        var proxyUnidadUsada = storeUnidadUsada.getProxy();

        var objJsonData = new Object();
        objJsonData.page  = storeUnidadUsada.currentPage;
        objJsonData.start = (storeUnidadUsada.currentPage - 1) * storeUnidadUsada.pageSize;
        objJsonData.limit = storeUnidadUsada.pageSize;
        objJsonData.filtroEstado = elf.readElement('cbxFiltroEstado');

        var objBuscaUnidadUsada = Ext.getCmp('formAplicacion').objBuscaUnidadUsada;

        if(objBuscaUnidadUsada !== undefined){
            objJsonData.codigoBusca = objBuscaUnidadUsada.codigo;

        }

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiUnidadUsada';
        objJsonRequest.apiMethod     = 'listaUnidadUsada';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        proxyUnidadUsada.api.read    = elf.setApiDataBridge(objJsonRequest.apiController);
        proxyUnidadUsada.extraParams = objJsonRequest;

    }

});