/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelCliente',
        'modelEstadoCliente',
        'modelGridEstadoCliente'
    ],
    stores: [
        'storeCliente',
        'storeEstadoCliente',
        'storeGridEstadoCliente'
    ],
    views: [
        'formAplicacion',
        'winCliente',
        'winParametrosBusqueda'
    ],
    name: 'hwtCatCliente',

    launch: function() {
        Ext.create('hwtCatCliente.view.formAplicacion', {renderTo: Ext.getBody()});
        elf.defaultDataApp();

        appLocal = this.getApplication();
        Ext.EventManager.onWindowResize(function(w, h){
            appLocal.ajustarVentana();
        });

        appLocal.ajustarVentana();
        Ext.getCmp('formAplicacion').extraeOpciones();

    },

    ajustarVentana: function() {
        elf.renderInterface(
            'formAplicacion',
            'gridCliente',
            58);
    }

});
