/*
 * File: app/store/storeReporteCondicion.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProCondicionUnidad.store.storeReporteCondicion', {
    extend: 'Ext.data.Store',

    requires: [
        'hwtProCondicionUnidad.model.modelReporteCondicion',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 250,
            storeId: 'storeReporteCondicion',
            model: 'hwtProCondicionUnidad.model.modelReporteCondicion',
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json',
                    rootProperty: function(data) {
                        var storeReporteCondicion = Ext.getStore('storeReporteCondicion');
                        var rawData = storeReporteCondicion.getProxy().getReader().rawData;
                        return rawData.hwtReporteCondicion;
                    }
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        var storeReporteCondicion = Ext.getStore('storeReporteCondicion');
        var proxyReporteCondicion = storeReporteCondicion.getProxy();

        var objJsonData = new Object();
        objJsonData.page  = storeReporteCondicion.currentPage;
        objJsonData.start = (storeReporteCondicion.currentPage - 1) * storeReporteCondicion.pageSize;
        objJsonData.limit = storeReporteCondicion.pageSize;

        /*
        var formParametrosBusqueda = Ext.getCmp('formParametrosBusqueda');

        if(formParametrosBusqueda !== undefined){
            objJsonData.paramCodigo      = elf.readElement('fiParamCodigo');
            objJsonData.paramNombreCorto = elf.readElement('fiParamNombreCorto');
            objJsonData.paramRazonSocial = elf.readElement('fiParamRazonSocial');
            objJsonData.paramRFC         = elf.readElement('fiParamRFC');
        }
        */

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiCondicionUnidad';
        objJsonRequest.apiMethod     = 'listaReporteCondicion';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        proxyReporteCondicion.api.read    = elf.setApiDataBridge(objJsonRequest.apiController);
        proxyReporteCondicion.extraParams = objJsonRequest;

    }

});