/*
 * File: app/view/winBuscaPedido.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProPedidoVentas.view.winBuscaPedido', {
    extend: 'Ext.window.Window',
    alias: 'widget.winBuscaPedido',

    requires: [
        'hwtProPedidoVentas.view.winBuscaPedidoViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.resizer.Splitter',
        'Ext.form.field.Date'
    ],

    viewModel: {
        type: 'winbuscapedido'
    },
    modal: true,
    id: 'winBuscaPedido',
    itemId: 'winBuscaPedido',
    width: 600,
    closable: false,
    title: 'Busqueda de Pedidos',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            cls: 'toolbarBackground',
            dock: 'bottom',
            id: 'toolbarBuscaPedido',
            itemId: 'toolbarBuscaPedido',
            items: [
                {
                    xtype: 'button',
                    id: 'btnConfirmarBusqueda',
                    itemId: 'btnConfirmarBusqueda',
                    width: 130,
                    iconCls: 'fa fa-search icon16 iconColorGreen',
                    text: 'Buscar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnConfirmarBusquedaClick'
                    }
                },
                {
                    xtype: 'tbfill',
                    id: 'fillBusca'
                },
                {
                    xtype: 'button',
                    id: 'btnCerrarBusqueda',
                    itemId: 'btnCerrarBusqueda',
                    width: 130,
                    iconCls: 'fa fa-window-close icon16 iconColorRed',
                    text: 'Cerrar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnCerrarBusquedaClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            preparaInterfaz: function() {
                var arrayCombos = new Array();

                var objConfig   = new Object();
                objConfig.idComboBox   = 'cbxBuscaGerenteRegional';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id           = 'opcionesBuscaGerenteRegional';
                objConfig.fieldValue   = 'usuario';
                objConfig.fieldDisplay = 'nombre';
                objConfig.filterDefault  = 'todo';
                arrayCombos.push(objConfig);

                var objConfig   = new Object();
                objConfig.idComboBox   = 'cbxBuscaVendedor';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id           = 'opcionesBuscaVendedor';
                objConfig.fieldValue   = 'usuario';
                objConfig.fieldDisplay = 'nombre';
                objConfig.filterDefault  = 'todo';
                arrayCombos.push(objConfig);

                var objConfig   = new Object();
                objConfig.idComboBox   = 'cbxBuscaConsecionario';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id           = 'opcionesBuscaConsecionario';
                objConfig.fieldValue   = 'codigo_consecionario';
                objConfig.fieldDisplay = 'descripcion';
                objConfig.filterDefault  = 'todo';
                arrayCombos.push(objConfig);

                arrayCombos.forEach(Ext.getCmp('formAplicacion').cargaCombosConfig);

                dtFechaInicio = new Date(new Date().getFullYear(), 0, 1);
                dtFechaFinal = new Date();

                elf.writeElement('dtBuscaFechaInicial',dtFechaInicio);
                elf.writeElement('dtBuscaFechaFinal',dtFechaFinal);


                var arrayCombos = new Array();

                var objConfig   = new Object();
                objConfig.idComboBox   = 'cbxBuscaSituacionInicial';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id           = 'opcionesBuscaSituacionPedido';
                objConfig.fieldValue   = 'codigo';
                objConfig.fieldDisplay = 'descripcion';
                objConfig.filterValue  = undefined;
                arrayCombos.push(objConfig);

                var objConfig   = new Object();
                objConfig.idComboBox   = 'cbxBuscaSituacionFinal';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id           = 'opcionesBuscaSituacionPedido';
                objConfig.fieldValue   = 'codigo';
                objConfig.fieldDisplay = 'descripcion';
                objConfig.filterValue  = '6';
                objConfig.filterDefault  = '6';
                arrayCombos.push(objConfig);
                arrayCombos.forEach(Ext.getCmp('formAplicacion').cargaCombosConfig);
            },
            id: 'formBuscaPedido',
            itemId: 'formBuscaPedido',
            bodyCls: 'formBackground',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    id: 'fieldsetFiltroVentas',
                    itemId: 'fieldsetFiltroVentas',
                    layout: 'column',
                    title: '<b>Filtro de Ventas</b>',
                    items: [
                        {
                            xtype: 'combobox',
                            columnWidth: 1,
                            id: 'cbxBuscaGerenteRegional',
                            itemId: 'cbxBuscaGerenteRegional',
                            margin: '0 3 3 0',
                            maxWidth: 450,
                            fieldLabel: 'Gerente',
                            labelWidth: 90,
                            editable: false,
                            displayField: 'nombre',
                            queryMode: 'local',
                            store: 'storeBuscaGerenteRegional',
                            valueField: 'usuario'
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 1,
                            id: 'cbxBuscaVendedor',
                            itemId: 'cbxBuscaVendedor',
                            margin: '0 3 3 0',
                            maxWidth: 450,
                            fieldLabel: 'Vendedor',
                            labelWidth: 90,
                            editable: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    id: 'fieldsetConsecionario',
                    itemId: 'fieldsetConsecionario',
                    layout: 'column',
                    title: '<b>Filtro de Consecionario</b>',
                    items: [
                        {
                            xtype: 'combobox',
                            columnWidth: 1,
                            id: 'cbxBuscaConsecionario',
                            itemId: 'cbxBuscaConsecionario',
                            margin: '0 3 3 0',
                            maxWidth: 450,
                            fieldLabel: 'Consecionario',
                            labelWidth: 90,
                            editable: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    id: 'fieldsetEspecificos',
                    itemId: 'fieldsetEspecificos',
                    layout: 'column',
                    title: '<b>Filtros Específicos</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.4,
                            id: 'tfBuscaCliente',
                            margin: '0 0 3 0',
                            fieldLabel: 'Cliente',
                            labelWidth: 90
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.05,
                            cls: 'botonZoomWindow',
                            id: 'btnZoomBuscaCliente',
                            itemId: 'btnZoomBuscaCliente',
                            margin: '0 0 3 0',
                            iconCls: 'fa fa-search icon16 iconColorWhite',
                            listeners: {
                                click: 'onBtnZoomBuscaClienteClick'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.55,
                            disabled: true,
                            disabledCls: 'disabledField',
                            id: 'tfBuscaClienteDescripcion',
                            itemId: 'tfBuscaClienteDescripcion',
                            margin: '0 0 3 0'
                        },
                        {
                            xtype: 'splitter',
                            columnWidth: 1,
                            height: 0,
                            id: 'splitterBusca'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.4,
                            id: 'tfBuscaUnidad',
                            itemId: 'tfBuscaUnidad',
                            margin: '0 0 3 0',
                            fieldLabel: 'Unidad',
                            labelWidth: 90
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.05,
                            cls: 'botonZoomWindow',
                            id: 'btnZoomBuscaUnidad',
                            itemId: 'btnZoomBuscaUnidad',
                            margin: '0 0 3 0',
                            iconCls: 'fa fa-search icon16 iconColorWhite',
                            listeners: {
                                click: 'onBtnZoomBuscaUnidadClick'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.55,
                            disabled: true,
                            disabledCls: 'disabledField',
                            id: 'tfBuscaUnidadDescripcion',
                            itemId: 'tfBuscaUnidadDescripcion',
                            margin: '0 0 3 0'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    id: 'fieldsetFiltroPedido',
                    itemId: 'fieldsetFiltroPedido',
                    title: '<b>Filtro de Pedido</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'tfBuscaPedido',
                            itemId: 'tfBuscaPedido',
                            margin: '0 3 3 0',
                            fieldLabel: 'Pedido',
                            labelWidth: 90
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    id: 'fieldsetRangoBusqueda',
                    itemId: 'fieldsetRangoBusqueda',
                    layout: 'column',
                    title: '<b>Rango de Búsqueda</b>',
                    items: [
                        {
                            xtype: 'datefield',
                            columnWidth: 0.5,
                            id: 'dtBuscaFechaInicial',
                            itemId: 'dtBuscaFechaInicial',
                            margin: '0 3 3 0',
                            fieldLabel: 'Fecha Inicial',
                            labelWidth: 90
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.5,
                            id: 'dtBuscaFechaFinal',
                            itemId: 'dtBuscaFechaFinal',
                            margin: '0 3 3 0',
                            fieldLabel: 'Fecha Final',
                            labelWidth: 90
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.5,
                            id: 'cbxBuscaSituacionInicial',
                            itemId: 'cbxBuscaSituacionInicial',
                            margin: '0 3 3 0',
                            fieldLabel: 'Situación Inicial',
                            labelWidth: 90,
                            editable: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.5,
                            id: 'cbxBuscaSituacionFinal',
                            itemId: 'cbxBuscaSituacionFinal',
                            margin: '0 3 3 0',
                            fieldLabel: 'Situación Final',
                            labelWidth: 90,
                            editable: false
                        }
                    ]
                }
            ]
        }
    ],

    onBtnConfirmarBusquedaClick: function(button, e, eOpts) {
        var arrayBusqueda = new Array();
        arrayBusqueda.push('cbxBuscaGerenteRegional');
        arrayBusqueda.push('cbxBuscaVendedor');
        arrayBusqueda.push('cbxBuscaConsecionario');
        arrayBusqueda.push('tfBuscaCliente');
        arrayBusqueda.push('tfBuscaUnidad');
        arrayBusqueda.push('dtBuscaFechaInicial');
        arrayBusqueda.push('dtBuscaFechaFinal');
        arrayBusqueda.push('cbxBuscaSituacionInicial');
        arrayBusqueda.push('cbxBuscaSituacionFinal');

        Ext.getStore('storePedidoVenta').arrayBusqueda = arrayBusqueda;
        elf.refreshGrid('gridPedidoVenta');
    },

    onBtnCerrarBusquedaClick: function(button, e, eOpts) {
        Ext.getStore('storePedidoVenta').arrayBusqueda = undefined;
        elf.closeWindow('winBuscaPedido');
    },

    onBtnZoomBuscaClienteClick: function(button, e, eOpts) {
        var arrayCamposDespliegue = new Array();

        var objCampo = new Object();
        objCampo.campoForm = 'tfBuscaCliente';
        objCampo.campoDato = 'codigo_cliente';
        arrayCamposDespliegue.push(objCampo);

        var objCampo = new Object();
        objCampo.campoForm = 'tfBuscaClienteDescripcion';
        objCampo.campoDato = 'razon_social';
        arrayCamposDespliegue.push(objCampo);

        elf.openWindow('winBuscaCliente');

        Ext.getCmp('formBuscaCliente').arrayCamposDespliegue = arrayCamposDespliegue;

        elf.refreshGrid('gridBuscaCliente');
    },

    onBtnZoomBuscaUnidadClick: function(button, e, eOpts) {
        var arrayCamposDespliegue = new Array();

        var objCampo = new Object();
        objCampo.campoForm = 'tfBuscaUnidad';
        objCampo.campoDato = 'codigo';
        arrayCamposDespliegue.push(objCampo);

        var objCampo = new Object();
        objCampo.campoForm = 'tfBuscaUnidadDescripcion';
        objCampo.campoDato = 'modelo';
        arrayCamposDespliegue.push(objCampo);

        elf.openWindow('winBuscaVin');
        var arrayCombos = new Array();
        arrayCombos.push('FiltroModelo');
        arrayCombos.push('FiltroMarca');
        arrayCombos.forEach(elf.loadCombos);

        Ext.getCmp('formBuscaVin').arrayCamposDespliegue = arrayCamposDespliegue;

        Ext.getStore('storeBuscaVin').filtroEstado = 'todo';
        elf.refreshGrid('gridBuscaVin');
    }

});