/*
 * File: app/model/modelCliente.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtCatCliente.model.modelCliente', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'rowid'
        },
        {
            name: 'codigo_cliente'
        },
        {
            name: 'nombre_corto'
        },
        {
            name: 'razon_social'
        },
        {
            name: 'rfc'
        },
        {
            name: 'dir_calle'
        },
        {
            name: 'dir_num_interior'
        },
        {
            name: 'dir_num_exterior'
        },
        {
            name: 'dir_colonia'
        },
        {
            name: 'dir_municipio'
        },
        {
            name: 'dir_estado'
        },
        {
            name: 'dir_pais'
        },
        {
            name: 'codigo_postal'
        },
        {
            name: 'representante_legal'
        },
        {
            name: 'contacto_nombre'
        },
        {
            name: 'contacto_telefono'
        },
        {
            name: 'contacto_movil'
        },
        {
            name: 'contacto_email'
        },
        {
            name: 'facturacion_email'
        }
    ]
});