/*
 * File: app/model/modelReporteCondicionLinea.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProCondicionUnidad.model.modelReporteCondicionLinea', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'rowid'
        },
        {
            name: 'num_reporte'
        },
        {
            name: 'num_sequencia'
        },
        {
            name: 'cod_seccion'
        },
        {
            name: 'cod_caracteristica'
        },
        {
            name: 'estado'
        },
        {
            name: 'observaciones'
        },
        {
            name: 'fotografia'
        },
        {
            name: 'valor_referencia'
        },
        {
            name: 'desc_caracteristica'
        },
        {
            name: 'precio_unitario_estimado'
        }
    ]
});