/*
 * File: app/view/winWorkplace.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtEsritorio.view.winWorkplace', {
    extend: 'Ext.container.Container',
    alias: 'widget.winWorkplace',

    requires: [
        'hwtEsritorio.view.winWorkplaceViewModel',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.form.Label',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'hwtEscritorio'
    },
    autoShow: true,
    id: 'winWorkplace',
    itemId: 'winWorkplace',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'formWorkplace',
            itemId: 'formWorkplace',
            layout: 'fit',
            bodyPadding: 10,
            manageHeight: false,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    cls: 'toolbarBackground',
                    dock: 'top',
                    id: 'toolbarWorkplace',
                    itemId: 'toolbarWorkplace',
                    items: [
                        {
                            xtype: 'tbfill',
                            id: 'filWorkplace',
                            itemId: 'filWorkplace'
                        },
                        {
                            xtype: 'button',
                            height: 24,
                            id: 'btnExitWorkspace',
                            itemId: 'btnExitWorkspace',
                            width: 130,
                            iconCls: 'ion-power icon16red',
                            text: 'Cerrar Sesión',
                            textAlign: 'left',
                            listeners: {
                                click: 'onBtnExitWorkspaceClick'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    border: false,
                    height: 140,
                    id: 'formHeader',
                    itemId: 'formHeader',
                    maxHeight: 140,
                    layout: 'column',
                    bodyCls: 'imagenAmbienteMenu',
                    items: [
                        {
                            xtype: 'image',
                            columnWidth: 0.2,
                            height: 130,
                            id: 'imgLogoCompany',
                            itemId: 'imgLogoCompany',
                            margin: '5 0 0 60',
                            maxHeight: 130,
                            maxWidth: 130,
                            shrinkWrap: 0,
                            width: 130,
                            src: '../../recurso/imagen/hwt_logo_gestion.png'
                        },
                        {
                            xtype: 'fieldset',
                            columnWidth: 0.8,
                            border: 0,
                            id: 'fieldsetSessionData',
                            itemId: 'fieldsetSessionData',
                            margin: '20 0 0 30',
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'label',
                                    columnWidth: 1,
                                    cls: 'fontBigTitle',
                                    id: 'lblCompany',
                                    itemId: 'lblCompany',
                                    margin: '0 0 20 0',
                                    padding: '10 0 10 45',
                                    text: 'Company'
                                },
                                {
                                    xtype: 'label',
                                    columnWidth: 0.5,
                                    focusOnToFront: false,
                                    cls: 'fontMediumTitle',
                                    id: 'lblUserName',
                                    itemId: 'lblUserName',
                                    padding: '7 0 5 45',
                                    text: 'User Name'
                                },
                                {
                                    xtype: 'label',
                                    columnWidth: 0.5,
                                    focusOnToFront: false,
                                    cls: 'fontMediumTitleRight',
                                    id: 'lblSystemName',
                                    itemId: 'lblSystemName',
                                    padding: '7 0 5 0',
                                    text: 'System Name'
                                },
                                {
                                    xtype: 'label',
                                    columnWidth: 0.5,
                                    focusOnToFront: false,
                                    cls: 'fontNormalTitle',
                                    id: 'lblProfile',
                                    itemId: 'lblProfile',
                                    padding: '0 0 5 45',
                                    text: 'Profile'
                                },
                                {
                                    xtype: 'label',
                                    columnWidth: 0.5,
                                    focusOnToFront: false,
                                    cls: 'fontNormalTitleRight',
                                    id: 'lblVersion',
                                    itemId: 'lblVersion',
                                    padding: '0 0 5 0',
                                    text: 'Version'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    id: 'tabPanelWorkplace',
                    itemId: 'tabPanelWorkplace',
                    items: [
                        {
                            xtype: 'panel',
                            id: 'tabTasks',
                            itemId: 'tabTasks',
                            bodyCls: 'formBackground',
                            title: 'Procesos',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'tabConfigTasks',
                                itemId: 'tabConfigTasks',
                                width: 120,
                                iconCls: 'ion-briefcase icon24',
                                textAlign: 'left'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetModuleProcess',
                                    itemId: 'fieldsetModuleProcess',
                                    margin: '5 20 10 20',
                                    layout: 'column',
                                    title: '<b>Gestión</b>',
                                    items: [
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnProManUnidadesUsadas',
                                            itemId: 'btnProManUnidadesUsadas',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-truck fa-lg icono-blanco icon24',
                                            text: 'Unidades</br>Usadas',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnProUnidadesUsadasClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnProCondicionUnidad',
                                            itemId: 'btnProCondicionUnidad',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-tachometer fa-lg icono-blanco icon24',
                                            text: 'Condición de la</br>Unidad',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnCondicionUnidadClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetModuleSales',
                                    itemId: 'fieldsetModuleSales',
                                    margin: '5 20 10 20',
                                    layout: 'column',
                                    title: '<b>Ventas</b>',
                                    items: [
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnProManCotizaciones',
                                            itemId: 'btnProManCotizaciones',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-wpforms fa-lg icono-blanco icon24',
                                            text: 'Cotización</br>Seminuevos',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnProManCotizacionesClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnProPedidoVentas',
                                            itemId: 'btnProPedidoVentas',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-usd fa-lg icono-blanco icon24',
                                            text: 'Pedido de Venta</br>de Unidades',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnProPedidoVentasClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetModuleProspect',
                                    itemId: 'fieldsetModuleProspect',
                                    margin: '5 20 10 20',
                                    layout: 'column',
                                    title: '<b>Prospectos</b>',
                                    items: [
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnProOportunidadVenta',
                                            itemId: 'btnProOportunidadVenta',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-briefcase fa-lg icono-blanco icon24',
                                            text: 'Oportunidad</br>de Venta',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnProOportunidadVentaClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetModuleSales1',
                                    itemId: 'fieldsetModuleSales1',
                                    margin: '5 20 10 20',
                                    layout: 'column',
                                    title: '<b>Compras</b>',
                                    items: [
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnProPropuestaAdquisicionUnidades',
                                            itemId: 'btnProPropuestaAdquisicionUnidades',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-check-square-o fa-lg icono-blanco icon24',
                                            text: 'Propuesta de</br>Adquisicion',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnProPropuestaAdquiscionUnidadesClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'tabCatalogs',
                            itemId: 'tabCatalogs',
                            layout: 'column',
                            bodyCls: 'formBackground',
                            title: 'Catalogos',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'tabConfigCatalogs',
                                itemId: 'tabConfigCatalogs',
                                width: 120,
                                iconCls: 'ion-ios-folder icon24',
                                textAlign: 'left'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    columnWidth: 1,
                                    id: 'fieldsetMainCatalogs',
                                    itemId: 'fieldsetMainCatalogs',
                                    margin: '5 20 10 20',
                                    layout: 'column',
                                    title: '<b>Principales</b>',
                                    items: [
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnCatCliente',
                                            itemId: 'btnCatCliente',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-handshake-o fa-lg icono-blanco icon24',
                                            text: '&nbspClientes',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnCatClienteClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnCatProveedor',
                                            itemId: 'btnCatProveedor',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-id-card-o fa-lg icono-blanco icon24',
                                            text: '&nbspProveedores',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnCatProveedorClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'tabQueries',
                            itemId: 'tabQueries',
                            bodyCls: 'formBackground',
                            title: 'Consultas',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'tabConfigQueries',
                                itemId: 'tabConfigQueries',
                                width: 120,
                                iconCls: 'ion-ios-paper icon24',
                                textAlign: 'left'
                            }
                        },
                        {
                            xtype: 'panel',
                            height: 500,
                            id: 'tabReports',
                            itemId: 'tabReports',
                            bodyCls: 'formBackground',
                            title: 'Reportes',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'tabConfigReports',
                                itemId: 'tabConfigReports',
                                width: 120,
                                iconCls: 'ion-printer icon24',
                                textAlign: 'left'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetReports',
                                    itemId: 'fieldsetReports',
                                    margin: '5 20 10 20',
                                    layout: 'column',
                                    title: '<b>Ventas</b>',
                                    items: [
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnRepVentas',
                                            itemId: 'btnRepVentas',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-file-excel-o fa-lg icono-blanco icon24',
                                            text: 'Reporte de</br>Ventas',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnCatClienteClick12'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 500,
                            id: 'tabSystem',
                            itemId: 'tabSystem',
                            bodyCls: 'formBackground',
                            title: 'Sistema',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'tabConfigSystem',
                                itemId: 'tabConfigSystem',
                                width: 120,
                                iconCls: 'ion-social-buffer icon24',
                                textAlign: 'left'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetSystemCatalogs',
                                    itemId: 'fieldsetSystemCatalogs',
                                    margin: '5 20 10 20',
                                    layout: 'column',
                                    title: '<b>Sistema</b>',
                                    items: [
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnSysLimpiarCache',
                                            itemId: 'btnSysLimpiarCache',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-database fa-lg icono-blanco icon24',
                                            text: 'Limpiar Cache',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnSysLimpiarCacheClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnMuestraPhpError',
                                            itemId: 'btnSysLimpiarCache1',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-file-code-o fa-lg icono-blanco icon24',
                                            text: 'Muestra</br>Errores PHP',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnMuestraPhpErrorClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.2,
                                            cls: 'botonZoom',
                                            height: 45,
                                            id: 'btnSysLimpiarPhpErrorLog',
                                            itemId: 'btnSysLimpiarPhpErrorLog',
                                            margin: '10 10 10 10',
                                            maxWidth: 170,
                                            iconCls: 'fa fa-trash-o fa-lg icono-blanco icon24',
                                            text: 'Elimina Archivo<br>PHP Error Log',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnSysLimpiarPhpErrorLogClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                resize: 'onFormWorkplaceResize'
            }
        }
    ],
    listeners: {
        resize: 'onWinWorkplaceResize'
    },

    onBtnExitWorkspaceClick: function(button, e, eOpts) {
        sessionStorage.clear();
        self.location="../hwtAcceso/index.html";
    },

    onBtnProUnidadesUsadasClick: function(button, e, eOpts) {
        elf.showAppWindow('hwtProUnidades','Mantenimiento a Unidades', true);
    },

    onBtnCondicionUnidadClick: function(button, e, eOpts) {
        elf.showAppWindow('hwtProCondicionUnidad','Condición de Unidades', true);
    },

    onBtnProManCotizacionesClick: function(button, e, eOpts) {
        elf.showAppWindow('hwtProCotizacion','Cotizacion de Unidades', true);
    },

    onBtnProPedidoVentasClick: function(button, e, eOpts) {
         elf.showAppWindow('hwtProPedidoVentas','Pedidos de Venta', true);
    },

    onBtnProOportunidadVentaClick: function(button, e, eOpts) {
        elf.showAppWindow('hwtProOportunidadVenta','Oportunidades de Venta', true);
    },

    onBtnProPropuestaAdquiscionUnidadesClick: function (button, e, eOpts) {
        elf.showAppWindow('hwtProPropuestaAdquisicion', 'Propuesta de Adquisición de Unidades', true);
    },

    onBtnCatClienteClick: function(button, e, eOpts) {
        elf.showAppWindow('hwtCatCliente','Catálogo de Clientes', true);
    },

    onBtnCatProveedorClick: function(button, e, eOpts) {
        elf.showAppWindow('hwtCatProveedor','Catálogo de Proveedores', true);
    },

    onBtnCatClienteClick12: function(button, e, eOpts) {
        var msgTipo = 'information';
        var msgTitulo = 'Catálogo de Cliente';
        var msgContenido = 'Ésta funcionalidad está en Fase de Desarrollo.';
        var msgFuncion = undefined;
        var msgFormato = undefined;
        elf.message(msgTipo,
                    msgTitulo,
                    msgContenido,
                    msgFuncion,
                    msgFormato
                   );
    },

    onBtnSysLimpiarCacheClick: function(button, e, eOpts) {
        var msgFuncion = function(){
            var apiController = 'sysApiCache';
            var apiMethod     = 'limpiaCache';
            var objJsonData    = new Object();
            objJsonData.accion = 'limpiaCache';

            var objJsonRequest = new Object();
            objJsonRequest.apiController = apiController;
            objJsonRequest.apiMethod     = apiMethod;
            objJsonRequest.apiData       = JSON.stringify(objJsonData);

            var functionSuccess = function(){
                var jsonData = elf.getInfoDataBridge('limpiaCache');
                elf.showInfo(jsonData,'information');
            };

            var functionFailure = function(){
                var jsonData = elf.getInfoDataBridge('limpiaCache');
                elf.showInfo(jsonData,'error');
            };


            elf.doDataBridge(objJsonRequest,
                             functionSuccess,
                             null,
                             functionFailure,
                             null);

        };
        msgTipo      = 'question';
        msgTitulo    = 'Cache de la Aplicación';
        msgContenido = 'Desea limpiar el Cache de la Aplicación (Flush)?';

        elf.message(msgTipo, msgTitulo, msgContenido, msgFuncion);
    },

    onBtnMuestraPhpErrorClick: function (button, e, eOpts) {
        elf.showUrlWindow('winPHPErrorLog',
            'Errores PHP de la Aplicacion',
            false,
            '../../recurso/clase/PHPError/index.php');
    },

    onBtnSysLimpiarPhpErrorLogClick: function (button, e, eOpts) {
        var msgFuncion = function () {
            var apiController = 'sysApiDeveloper';
            var apiMethod = 'eliminaPHPErrorLog';
            var objJsonData = new Object();
            objJsonData.accion = 'eliminaPHPErrorLog';

            var objJsonRequest = new Object();
            objJsonRequest.apiController = apiController;
            objJsonRequest.apiMethod = apiMethod;
            objJsonRequest.apiData = JSON.stringify(objJsonData);

            var functionSuccess = function () {
                var jsonData = elf.getInfoDataBridge('eliminaPHPErrorLog');
                elf.showInfo(jsonData, 'information');
            };

            var functionFailure = function () {
                var jsonData = elf.getInfoDataBridge('eliminaPHPErrorLog');
                elf.showInfo(jsonData, 'error');
            };


            elf.doDataBridge(objJsonRequest,
                functionSuccess,
                null,
                functionFailure,
                null);

        };
        msgTipo = 'question';
        msgTitulo = 'Archivo LOG de Errores PHP';
        msgContenido = 'Desea depurar el Archivo LOG de Errores PHP?';

        elf.message(msgTipo,msgTitulo,msgContenido,msgFuncion);
    },

    onFormWorkplaceResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
        if (typeof appLocal !== 'undefined') {
            appLocal.renderInterface();
        }

    },

    onWinWorkplaceResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
        console.log('ventana resizadsa');
        if (typeof appLocal !== 'undefined') {
            appLocal.renderInterface();
        }
    }

});