/*
 * File: app/view/formAcceso.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtAcceso.view.formAcceso', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formAcceso',

    requires: [
        'hwtAcceso.view.formAccesoViewModel',
        'Ext.form.FieldSet',
        'Ext.Img',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'formAcceso'
    },
    id: 'formAcceso',
    itemId: 'formAcceso',
    layout: 'column',
    bodyCls: 'formBackground',
    bodyPadding: 10,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'fieldset',
            columnWidth: 1,
            border: 0,
            height: 220,
            id: 'fieldsetEncabezado',
            itemId: 'fieldsetEncabezado'
        },
        {
            xtype: 'fieldset',
            columnWidth: 0.5,
            border: 0,
            height: 250,
            id: 'fieldsetImage',
            itemId: 'fieldsetImage',
            items: [
                {
                    xtype: 'image',
                    height: 201,
                    margin: '0 0 0 250',
                    width: 201,
                    src: '../../recurso/imagen/hwt_logo_gestion.png'
                }
            ]
        },
        {
            xtype: 'fieldset',
            columnWidth: 0.3,
            border: 0,
            height: 250,
            id: 'fieldsetAcceso',
            itemId: 'fieldsetAcceso',
            layout: 'column',
            items: [
                {
                    xtype: 'textfield',
                    columnWidth: 1,
                    id: 'ftUsuario',
                    itemId: 'ftUsuario',
                    margin: '5 0 0 0',
                    maxWidth: 300,
                    width: 300,
                    fieldLabel: 'Usuario'
                },
                {
                    xtype: 'textfield',
                    columnWidth: 1,
                    id: 'ftAcceso',
                    itemId: 'ftAcceso',
                    margin: '5 0 0 0',
                    maxWidth: 300,
                    width: 300,
                    fieldLabel: 'Acceso',
                    inputType: 'password'
                },
                {
                    xtype: 'button',
                    columnWidth: 1,
                    baseCls: 'boton-negro',
                    height: 50,
                    id: 'btnAcceso',
                    itemId: 'btnAcceso',
                    margin: '5 0 0 105',
                    maxWidth: 195,
                    width: 195,
                    iconCls: 'fa fa-key fa-lg icono-blanco',
                    text: 'Acceder',
                    listeners: {
                        click: 'onButtonClick'
                    }
                }
            ]
        },
        {
            xtype: 'fieldset',
            columnWidth: 0.2,
            border: 0,
            height: 250
        },
        {
            xtype: 'fieldset',
            columnWidth: 1,
            border: 0,
            height: 200
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        Ext.getCmp('formAcceso').validarAcceso();
    },

    validarAcceso: function() {
        var objJsonData = new Object();
        objJsonData.usuario = elf.readElement('ftUsuario');
        objJsonData.acceso  = elf.readElement('ftAcceso');

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiAcceso';
        objJsonRequest.apiMethod     = 'validarAcceso';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        var functionSuccess = function(){
            var jsonData = elf.getInfoDataBridge('validarAcceso');
            console.log(jsonData);

            var objSession = new Object();
            objSession.company_code   = jsonData.sessionData.company_code;
            objSession.company_name   = jsonData.sessionData.company_name;
            objSession.user_id        = jsonData.sessionData.user_id;
            objSession.user_name      = jsonData.sessionData.user_name;
            objSession.user_profile   = jsonData.sessionData.user_profile;
            objSession.user_email     = jsonData.sessionData.user_email;
            objSession.profile_code   = jsonData.sessionData.profile_code;
            objSession.system_code    = jsonData.sessionData.system_code;
            objSession.system_name    = jsonData.sessionData.system_name;
            objSession.system_version = jsonData.sessionData.system_version;

            elf.generateSession(objSession);
            self.location="../hwtEscritorio/index.html";
        };

        var functionFailure = function(){
            var jsonData = elf.getInfoDataBridge('validarAcceso');
            elf.showInfo(jsonData, 'error', 'ftUsuario');
        };

        elf.doDataBridge(objJsonRequest,
                          functionSuccess,
                          null,
                          functionFailure,
                          null);
    }

});