/*
 * File: app/store/storeCotizacionUnidad.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProCotizacion.store.storeCotizacionUnidad', {
    extend: 'Ext.data.Store',

    requires: [
        'hwtProCotizacion.model.modCotizacionUnidad',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeCotizacionUnidad',
            model: 'hwtProCotizacion.model.modCotizacionUnidad',
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json',
                    rootProperty: function(data) {
                        var storeCotizacionUnidad = Ext.getStore('storeCotizacionUnidad');
                        var rawData = storeCotizacionUnidad.getProxy().getReader().rawData;
                        return rawData.hwtCotizacionUnidad;
                    }
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        var storeCotizacionUnidad = Ext.getStore('storeCotizacionUnidad');
        var proxyCliente = storeCotizacionUnidad.getProxy();

        var objJsonData = new Object();
        objJsonData.page  = storeCotizacionUnidad.currentPage;
        objJsonData.start = (storeCotizacionUnidad.currentPage - 1) * storeCotizacionUnidad.pageSize;
        objJsonData.limit = storeCotizacionUnidad.pageSize;
        objJsonData.tfNumCotizacion     = elf.readElement('tfNoCotizacion');


        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiCotizacion';
        objJsonRequest.apiMethod     = 'listaUnidadCotizacion';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        proxyCliente.api.read        = elf.setApiDataBridge(objJsonRequest.apiController);
        proxyCliente.extraParams     = objJsonRequest;
    }

});