/*
 * File: app/store/storeProveedor.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtCatProveedor.store.storeProveedor', {
    extend: 'Ext.data.Store',

    requires: [
        'hwtCatProveedor.model.modelProveedor',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 150,
            storeId: 'storeProveedor',
            model: 'hwtCatProveedor.model.modelProveedor',
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            },
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json',
                    rootProperty: function(data) {
                        var storeProveedor = Ext.getStore('storeProveedor');
                        var rawData = storeProveedor.getProxy().getReader().rawData;
                        return rawData.hwtProveedor;
                    }
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        var storeProveedor = Ext.getStore('storeProveedor');
        var proxyProveedor = storeProveedor.getProxy();

        var objJsonData = new Object();
        objJsonData.page  = storeProveedor.currentPage;
        objJsonData.start = (storeProveedor.currentPage - 1) * storeProveedor.pageSize;
        objJsonData.limit = storeProveedor.pageSize;
        objJsonData.filtroEstado = elf.readElement('cbxGridEstadoProveedor');

        var formParametrosBusqueda = Ext.getCmp('formParametrosBusqueda');

        if(formParametrosBusqueda !== undefined){
            objJsonData.paramCodigo      = elf.readElement('fiParamCodigo');
            objJsonData.paramNombreCorto = elf.readElement('fiParamNombreCorto');
            objJsonData.paramRazonSocial = elf.readElement('fiParamRazonSocial');
            objJsonData.paramRFC         = elf.readElement('fiParamRFC');
        }

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiProveedor';
        objJsonRequest.apiMethod     = 'listaProveedor';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        proxyProveedor.api.read    = elf.setApiDataBridge(objJsonRequest.apiController);
        proxyProveedor.extraParams = objJsonRequest;

    }

});