/*
 * File: app/store/storeOportunidadVenta.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProOportunidadVenta.store.storeOportunidadVenta', {
    extend: 'Ext.data.Store',

    requires: [
        'hwtProOportunidadVenta.model.modelOportunidadVenta',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeOportunidadVenta',
            model: 'hwtProOportunidadVenta.model.modelOportunidadVenta',
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json',
                    rootProperty: function (data) {
                        var storeOportunidadVenta = Ext.getStore('storeOportunidadVenta');
                        var rawData = storeOportunidadVenta.getProxy().getReader().rawData;
                        return rawData.hwtOportunidadVenta;
                    }
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function (store, operation, eOpts) {
        var storeOportunidadVenta = Ext.getStore('storeOportunidadVenta');
        var proxyOportunidadVenta = storeOportunidadVenta.getProxy();

        var objJsonData = new Object();
        objJsonData.page = storeOportunidadVenta.currentPage;
        objJsonData.start = (storeOportunidadVenta.currentPage - 1) * storeOportunidadVenta.pageSize;
        objJsonData.limit = storeOportunidadVenta.pageSize;
        objJsonData.filtroEstado = elf.readElement('cbxSituacionOportunidad');

        var objBuscaOportunidadVenta = Ext.getCmp('formAplicacion').objBuscaOportunidadVenta;

        if (objBuscaOportunidadVenta !== undefined) {
            objJsonData.codigoBusca = objBuscaOportunidadVenta.codigo;

        }

        if (store.arrayBusqueda !== undefined) {
            objJsonData.filtroEstado = 'BUSQUEDA';
            arrayBusqueda = store.arrayBusqueda;
            arrayBusqueda.forEach(function (element, index) {
                objJsonData[element] = elf.readElement(element);
            });

            elf.hideElement('cbxSituacionOportunidad');
            elf.showElement('btnLimpiaBusqueda');

        }
        else {
            elf.showElement('cbxSituacionOportunidad');
            elf.hideElement('btnLimpiaBusqueda');
        }

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiOportunidadVenta';
        objJsonRequest.apiMethod = 'listaOportunidadVenta';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        proxyOportunidadVenta.api.read = elf.setApiDataBridge(objJsonRequest.apiController);
        proxyOportunidadVenta.extraParams = objJsonRequest;

    }

});