/*
 * File: app/store/storePedidoVenta.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProPedidoVentas.store.storePedidoVenta', {
    extend: 'Ext.data.Store',

    requires: [
        'hwtProPedidoVentas.model.modPedidoVenta',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 100,
            storeId: 'storePedidoVenta',
            model: 'hwtProPedidoVentas.model.modPedidoVenta',
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            },
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json',
                    rootProperty: function(data) {
                        var storePedidoVenta = Ext.getStore('storePedidoVenta');
                        var rawData = storePedidoVenta.getProxy().getReader().rawData;
                        return rawData.hwtPedidoVenta;
                    }
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        var storePedidoVenta = Ext.getStore('storePedidoVenta');
        var proxyPedidoVenta = storePedidoVenta.getProxy();

        var objJsonData = new Object();
        objJsonData.page  = storePedidoVenta.currentPage;
        objJsonData.start = (storePedidoVenta.currentPage - 1) * storePedidoVenta.pageSize;
        objJsonData.limit = storePedidoVenta.pageSize;
        objJsonData.filtroEstado = elf.readElement('cbxFiltroSituacionPedido');

        var objBuscaPedidoVenta = Ext.getCmp('formAplicacion').objBuscaPedidoVenta;

        if(objBuscaPedidoVenta !== undefined){
            objJsonData.codigoBusca = objBuscaPedidoVenta.codigo;

        }

        if(store.arrayBusqueda !== undefined){
            objJsonData.filtroEstado = 'BUSQUEDA';
            arrayBusqueda = store.arrayBusqueda;
            arrayBusqueda.forEach(function(element,index){
                objJsonData[element] = elf.readElement(element);
            });

            elf.hideElement('cbxFiltroSituacionPedido');
            elf.showElement('btnLimpiaBusqueda');

        }
        else{
            elf.showElement('cbxFiltroSituacionPedido');
            elf.hideElement('btnLimpiaBusqueda');
        }

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiPedidoVenta';
        objJsonRequest.apiMethod     = 'listaPedidoVenta';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        proxyPedidoVenta.api.read    = elf.setApiDataBridge(objJsonRequest.apiController);
        proxyPedidoVenta.extraParams = objJsonRequest;

    }

});