/*
 * File: app/store/storePedidoVentaAdicional.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProPedidoVentas.store.storePedidoVentaAdicional', {
    extend: 'Ext.data.Store',

    requires: [
        'hwtProPedidoVentas.model.modPedidoVentaAdicional',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storePedidoVentaAdicional',
            model: 'hwtProPedidoVentas.model.modPedidoVentaAdicional',
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json',
                    rootProperty: function(data) {
                        var storePedidoVentaAdicional = Ext.getStore('storePedidoVentaAdicional');
                        var rawData = storePedidoVentaAdicional.getProxy().getReader().rawData;
                        return rawData.hwtPedidoVentaAdicional;
                    }
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        var storePedidoVentaAdicional = Ext.getStore('storePedidoVentaAdicional');
        var proxyCliente = storePedidoVentaAdicional.getProxy();

        var objJsonData = new Object();
        objJsonData.page        = storePedidoVentaAdicional.currentPage;
        objJsonData.start       = (storePedidoVentaAdicional.currentPage - 1) * storePedidoVentaAdicional.pageSize;
        objJsonData.limit       = storePedidoVentaAdicional.pageSize;
        objJsonData.tfNumPedido = elf.readElement('tfNumPedido');

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiPedidoVenta';
        objJsonRequest.apiMethod     = 'listaPedidoVentaAdicional';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        proxyCliente.api.read        = elf.setApiDataBridge(objJsonRequest.apiController);
        proxyCliente.extraParams     = objJsonRequest;
    }

});