/*
 * File: app/view/winOportunidadVenta.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProOportunidadVenta.view.winOportunidadVenta', {
    extend: 'Ext.window.Window',
    alias: 'widget.winOportunidadVenta',

    requires: [
        'hwtProOportunidadVenta.view.winOportunidadVentaViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.resizer.Splitter',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'winoportunidadventa'
    },
    modal: true,
    id: 'winOportunidadVenta',
    itemId: 'winOportunidadVenta',
    width: 550,
    bodyCls: 'formBackground',
    closable: false,
    title: 'Oportunidad de Venta',

    dockedItems: [
        {
            xtype: 'toolbar',
            cls: 'toolbarBackground',
            dock: 'bottom',
            id: 'toolbarOportunidadVenta',
            itemId: 'toolbarOportunidadVenta',
            items: [
                {
                    xtype: 'button',
                    id: 'btnConfirmarOportunidad',
                    itemId: 'btnConfirmarOportunidad',
                    width: 130,
                    iconCls: 'fa fa-check-square icon16 iconColorGreen',
                    text: 'Confirmar',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnCerrarOportunidad',
                    itemId: 'btnCerrarOportunidad',
                    width: 130,
                    iconCls: 'fa fa-window-close icon16 iconColorRed',
                    text: 'Cerrar',
                    textAlign: 'left'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            id: 'formOportunidadVenta',
            itemId: 'formOportunidadVenta',
            bodyCls: 'formBackground',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'tabPanelOportunidadVenta',
                    itemId: 'tabPanelOportunidadVenta',
                    bodyCls: 'formBackground',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 410,
                            id: 'tabGeneral',
                            itemId: 'tabGeneral',
                            bodyCls: 'formBackground',
                            title: 'General',
                            tabConfig: {
                                xtype: 'tab',
                                width: 130
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetInformacionVisita',
                                    itemId: 'fieldsetInformacionVisita',
                                    layout: 'column',
                                    title: '<b>Información de Oportunidad</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            id: 'tfNumOportunidad',
                                            itemId: 'tfNumOportunidad',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Número'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabled: true,
                                            disabledCls: 'disabledField',
                                            id: 'tfSituacionOportunidad',
                                            itemId: 'tfSituacionOportunidad',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Situación'
                                        },
                                        {
                                            xtype: 'datefield',
                                            columnWidth: 0.5,
                                            id: 'dtVisitaFecha',
                                            itemId: 'dtVisitaFecha',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Fecha'
                                        },
                                        {
                                            xtype: 'splitter',
                                            columnWidth: 1,
                                            height: 0
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabledCls: 'disabledField',
                                            id: 'tfVisitaAnn',
                                            itemId: 'tfVisitaAnn',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Año'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabledCls: 'disabledField',
                                            id: 'tfVisitaSemana',
                                            itemId: 'tfVisitaSemana',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Semana'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetInformacionSolicitante',
                                    itemId: 'fieldsetInformacionSolicitante',
                                    layout: 'column',
                                    title: '<b>Información del Solicitante</b>',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxTipoSolicitante',
                                            itemId: 'cbxTipoSolicitante',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Tipo Solicitante',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeTipoSolicitante',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxTipoEmpresa',
                                            itemId: 'cbxTipoEmpresa',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Tipo Empresa',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeTipoEmpresa',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.4,
                                            id: 'tfCodigoCliente',
                                            itemId: 'tfCodigoCliente',
                                            margin: '0 0 3 0',
                                            fieldLabel: 'Cliente'
                                        },
                                        {
                                            xtype: 'button',
                                            cls: 'botonZoomWindow',
                                            id: 'btnZoomCliente',
                                            itemId: 'btnZoomCliente',
                                            margin: '0 3 3 0',
                                            minWidth: 0.05,
                                            width: 30,
                                            iconCls: 'fa fa-search icon16 iconColorWhite'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.53,
                                            disabled: true,
                                            disabledCls: 'disabledField',
                                            id: 'tfRazonSocial',
                                            itemId: 'tfRazonSocial',
                                            margin: '0 3 3 0'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetNecesidadUnidades',
                                    itemId: 'fieldsetNecesidadUnidades',
                                    layout: 'column',
                                    title: '<b>Necesidad de Unidades</b>',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 0.5,
                                            id: 'cbxMarca',
                                            itemId: 'cbxMarca',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Marca',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeMarca',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 0.5,
                                            id: 'cbxModelo',
                                            itemId: 'cbxModelo',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Modelo',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeModelo',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            id: 'tfCantidad',
                                            itemId: 'tfCantidad',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Cantidad'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            columnWidth: 1,
                                            id: 'tfObservaciones',
                                            itemId: 'tfObservaciones',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Observaciones'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 410,
                            id: 'tabContacto',
                            itemId: 'tabContacto',
                            bodyCls: 'formBackground',
                            title: 'Contacto',
                            tabConfig: {
                                xtype: 'tab',
                                width: 130
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetInformacionVentas',
                                    itemId: 'fieldsetInformacionVentas',
                                    layout: 'column',
                                    title: '<b>Información de Ventas</b>',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxCodigoGerenteRegional',
                                            itemId: 'cbxCodigoGerenteRegional',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Gerente Regional',
                                            displayField: 'nombre',
                                            queryMode: 'local',
                                            store: 'storeCodigoGerenteRegional',
                                            valueField: 'usuario'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxCodigoVendedor',
                                            itemId: 'cbxCodigoVendedor',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Vendedor',
                                            editable: false,
                                            displayField: 'nombre',
                                            queryMode: 'local',
                                            store: 'storeCodigoVendedor',
                                            valueField: 'usuario'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxCodigoConsecionario',
                                            itemId: 'cbxCodigoConsecionario',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Consecionario',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeCodigoConsecionario',
                                            valueField: 'codigo_consecionario'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetDatosContacto',
                                    itemId: 'fieldsetDatosContacto',
                                    layout: 'column',
                                    title: '<b>Datos Contacto</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            id: 'tfContactoNombre',
                                            itemId: 'tfContactoNombre',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Nombre'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            id: 'tfContactoCargo',
                                            itemId: 'tfContactoCargo',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Cargo'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            id: 'tfContactoTelefono',
                                            itemId: 'tfContactoTelefono',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Teléfono'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            id: 'tfContactoMovil',
                                            itemId: 'tfContactoMovil',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Móvil'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            id: 'tfContactoEmail',
                                            itemId: 'tfContactoEmail',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Correo'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetDatosUbicacion',
                                    itemId: 'fieldsetDatosUbicacion',
                                    layout: 'column',
                                    title: '<b>Ubicación</b>',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxSolicitudPais',
                                            itemId: 'cbxSolicitudPais',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'País'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxSolicitudEstado',
                                            itemId: 'cbxSolicitudEstado',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Estado'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxSolicitudMunicipio',
                                            itemId: 'cbxSolicitudMunicipio',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Municipio'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxSolicitudCiudad',
                                            itemId: 'cbxSolicitudCiudad',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Ciudad'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            id: 'tfSolicitudCp',
                                            itemId: 'tfSolicitudCp',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Codigo Postal'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 410,
                            id: 'tabCotizaciones',
                            itemId: 'tabCotizaciones',
                            bodyCls: 'formBackground',
                            title: 'Cotizaciones',
                            tabConfig: {
                                xtype: 'tab',
                                width: 130
                            }
                        }
                    ]
                }
            ]
        }
    ]

});