/*
 * File: app/view/winOportunidadVenta.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProOportunidadVenta.view.winOportunidadVenta', {
    extend: 'Ext.window.Window',
    alias: 'widget.winOportunidadVenta',

    requires: [
        'hwtProOportunidadVenta.view.winOportunidadVentaViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.resizer.Splitter',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'winoportunidadventa'
    },
    modal: true,
    id: 'winOportunidadVenta',
    itemId: 'winOportunidadVenta',
    width: 550,
    bodyCls: 'formBackground',
    closable: false,
    title: 'Oportunidad de Venta',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            cls: 'toolbarBackground',
            dock: 'bottom',
            id: 'toolbarOportunidadVenta',
            itemId: 'toolbarOportunidadVenta',
            items: [
                {
                    xtype: 'button',
                    id: 'btnConfirmarOportunidad',
                    itemId: 'btnConfirmarOportunidad',
                    width: 130,
                    iconCls: 'fa fa-check-square icon16 iconColorGreen',
                    text: 'Confirmar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnConfirmarOportunidadClick'
                    }
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnCerrarOportunidad',
                    itemId: 'btnCerrarOportunidad',
                    width: 130,
                    iconCls: 'fa fa-window-close icon16 iconColorRed',
                    text: 'Cerrar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnCerrarOportunidadClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            preparaInterfaz: function (pFuncionCarga) {
                var arrayCombos = new Array();

                var objConfig = new Object();
                objConfig.idComboBox = 'cbxTipoSolicitante';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id = 'opcionesTipoSolicitante';
                objConfig.fieldValue = 'codigo';
                objConfig.fieldDisplay = 'descripcion';
                arrayCombos.push(objConfig);

                var objConfig = new Object();
                objConfig.idComboBox = 'cbxMarca';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id = 'opcionesMarca';
                objConfig.fieldValue = 'descripcion';
                objConfig.fieldDisplay = 'descripcion';
                arrayCombos.push(objConfig);

                var objConfig = new Object();
                objConfig.idComboBox = 'cbxModelo';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id = 'opcionesModelo';
                objConfig.fieldValue = 'descripcion';
                objConfig.fieldDisplay = 'descripcion';
                arrayCombos.push(objConfig);

                var objConfig = new Object();
                objConfig.idComboBox = 'cbxCodigoGerenteRegional';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id = 'opcionesGerenteRegional';
                objConfig.fieldValue = 'usuario';
                objConfig.fieldDisplay = 'nombre';
                arrayCombos.push(objConfig);

                var objConfig = new Object();
                objConfig.idComboBox = 'cbxCodigoVendedor';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id = 'opcionesVendedor';
                objConfig.fieldValue = 'usuario';
                objConfig.fieldDisplay = 'nombre';
                arrayCombos.push(objConfig);

                var objConfig = new Object();
                objConfig.idComboBox = 'cbxCodigoConsecionario';
                objConfig.idDataBridge = 'datosOpciones';
                objConfig.id = 'opcionesConsecionario';
                objConfig.fieldValue = 'codigo_consecionario';
                objConfig.fieldDisplay = 'descripcion';
                arrayCombos.push(objConfig);

                arrayCombos.forEach(elf.loadComboBoxConfig);

                console.log('Acaba de Cargar los Combos');

                if (Ext.getCmp('formOportunidadVenta').operacionOportunidadVenta === 'crear') {
                    var fechaActual = new Date();
                    elf.writeElement('dtVisitaFecha', fechaActual);

                    elf.writeElement('tfCantidadSolicitada', '0');
                    elf.writeElement('tfCantidadAtendida', '0');
                    elf.writeElement('tfCantidadSaldo', '0');
                }

                console.log('Prepara Interfaz');

                if (pFuncionCarga !== undefined) {
                    pFuncionCarga();
                }

            },
            obtieneLocalizacion: function (pTipo, pFuncionCarga) {
                var apiController = 'apiOportunidadVenta';
                var apiMethod = 'datosLocalizacion';

                var objJsonData = new Object();
                objJsonData.pais = elf.readElement('cbxSolicitudPais');
                objJsonData.estado = elf.readElement('cbxSolicitudEstado');
                objJsonData.municipio = elf.readElement('cbxSolicitudMunicipio');
                objJsonData.tipoDato = pTipo;

                var objJsonRequest = new Object();
                objJsonRequest.apiController = apiController;
                objJsonRequest.apiMethod = apiMethod;
                objJsonRequest.apiData = JSON.stringify(objJsonData);

                var functionSuccess = function () {
                    var jsonData = elf.getInfoDataBridge('datosLocalizacion');
                    pFuncionCarga();
                };

                var functionFailure = function () {
                    var jsonData = elf.getInfoDataBridge('datosLocalizacion');
                    elf.showInfo(jsonData, 'error');
                };


                elf.doDataBridge(objJsonRequest,
                    functionSuccess,
                    null,
                    functionFailure,
                    null);
            },
            grabaOportunidadVenta: function () {
                if (Ext.getCmp('formOportunidadVenta').isValid()) {
                    var formRegistro = 'formOportunidadVenta';
                    var apiController = 'apiOportunidadVenta';
                    var apiMethod = 'grabaOportunidadVenta';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = elf.prepareFormFields(formRegistro);

                    var functionSuccess = function () {
                        var jsonData = elf.getInfoDataBridge(apiMethod);

                        elf.showInfo(jsonData, 'information');

                        elf.closeWindow('winOportunidadVenta');
                        elf.refreshGrid('gridOportunidadVenta');
                    };

                    var functionFailure = function () {
                        var jsonData = elf.getInfoDataBridge(apiMethod);
                        elf.showInfo(jsonData, 'error', 'tfCodigoCliente');
                    };

                    elf.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);
                } //Formulario Valido
                else {
                    elf.message('error',
                        'Formulario Incompleto',
                        'Debe de llenar los Campos Requeridos');
                }
            },
            id: 'formOportunidadVenta',
            itemId: 'formOportunidadVenta',
            bodyCls: 'formBackground',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'tabPanelOportunidadVenta',
                    itemId: 'tabPanelOportunidadVenta',
                    bodyCls: 'formBackground',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 470,
                            id: 'tabGeneral',
                            itemId: 'tabGeneral',
                            bodyCls: 'formBackground',
                            title: 'General',
                            tabConfig: {
                                xtype: 'tab',
                                width: 130
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetInformacionVisita',
                                    itemId: 'fieldsetInformacionVisita',
                                    layout: 'column',
                                    title: '<b>Información de Oportunidad</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabled: true,
                                            disabledCls: 'disabledField',
                                            id: 'tfNumOportunidad',
                                            itemId: 'tfNumOportunidad',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Número',
                                            fieldCls: 'keyField'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabled: true,
                                            disabledCls: 'disabledField',
                                            id: 'tfSituacionOportunidad',
                                            itemId: 'tfSituacionOportunidad',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Situación',
                                            fieldCls: 'keyField'
                                        },
                                        {
                                            xtype: 'datefield',
                                            columnWidth: 0.5,
                                            disabledCls: 'disabledField',
                                            id: 'dtVisitaFecha',
                                            itemId: 'dtVisitaFecha',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Fecha',
                                            fieldCls: 'keyField',
                                            allowBlank: false,
                                            editable: false,
                                            listeners: {
                                                change: 'onDtVisitaFechaChange'
                                            }
                                        },
                                        {
                                            xtype: 'splitter',
                                            columnWidth: 1,
                                            height: 0
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabled: true,
                                            disabledCls: 'disabledField',
                                            id: 'tfVisitaSemana',
                                            itemId: 'tfVisitaSemana',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Semana',
                                            fieldCls: 'keyField',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabled: true,
                                            disabledCls: 'disabledField',
                                            id: 'tfVisitaAnn',
                                            itemId: 'tfVisitaAnn',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Año',
                                            fieldCls: 'keyField',
                                            allowBlank: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetInformacionSolicitante',
                                    itemId: 'fieldsetInformacionSolicitante',
                                    layout: 'column',
                                    title: '<b>Información del Solicitante</b>',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            disabledCls: 'disabledField',
                                            id: 'cbxTipoSolicitante',
                                            itemId: 'cbxTipoSolicitante',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Tipo Solicitante',
                                            fieldCls: 'keyField',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeTipoSolicitante',
                                            valueField: 'codigo',
                                            listeners: {
                                                change: 'onCbxTipoSolicitanteChange'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            disabledCls: 'disabledField',
                                            id: 'tfTipoEmpresa',
                                            itemId: 'tfTipoEmpresa',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Tipo Empresa',
                                            fieldCls: 'keyField',
                                            allowBlank: false,
                                            listeners: {
                                                change: 'onTfTipoEmpresaChange'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.4,
                                            disabledCls: 'disabledField',
                                            hidden: true,
                                            id: 'tfCodigoCliente',
                                            itemId: 'tfCodigoCliente',
                                            margin: '0 0 3 0',
                                            fieldLabel: 'Cliente',
                                            fieldCls: 'keyField'
                                        },
                                        {
                                            xtype: 'button',
                                            cls: 'botonZoomWindow',
                                            hidden: true,
                                            id: 'btnZoomCliente',
                                            itemId: 'btnZoomCliente',
                                            margin: '0 3 3 0',
                                            minWidth: 0.05,
                                            width: 30,
                                            iconCls: 'fa fa-search icon16 iconColorWhite',
                                            listeners: {
                                                click: 'onBtnZoomClienteClick'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            disabled: true,
                                            disabledCls: 'disabledField',
                                            id: 'tfRazonSocial',
                                            itemId: 'tfRazonSocial',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Razón Social',
                                            fieldCls: 'keyField',
                                            allowBlank: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetNecesidadUnidades',
                                    itemId: 'fieldsetNecesidadUnidades',
                                    layout: 'column',
                                    title: '<b>Necesidad de Unidades</b>',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 0.5,
                                            id: 'cbxMarca',
                                            itemId: 'cbxMarca',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Marca',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeMarca',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 0.5,
                                            id: 'cbxModelo',
                                            itemId: 'cbxModelo',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Modelo',
                                            editable: false,
                                            displayField: 'descripcion',
                                            queryMode: 'local',
                                            store: 'storeModelo',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'fieldset',
                                            columnWidth: 1,
                                            id: 'fieldsetCantidadUnidades',
                                            itemId: 'fieldsetCantidadUnidades',
                                            layout: 'column',
                                            title: '<b>Cantidad de Unidades</b>',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    columnWidth: 0.4,
                                                    id: 'tfCantidadSolicitada',
                                                    itemId: 'tfCantidadSolicitada',
                                                    margin: '0 3 3 0',
                                                    fieldLabel: 'Solicitadas',
                                                    labelWidth: 90,
                                                    allowBlank: false,
                                                    listeners: {
                                                        change: 'onTfCantidadSolicitadaChange'
                                                    }
                                                },
                                                {
                                                    xtype: 'splitter',
                                                    columnWidth: 1,
                                                    height: 0,
                                                    id: 'splitter',
                                                    itemId: 'splitter'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    columnWidth: 0.4,
                                                    disabled: true,
                                                    disabledCls: 'disabledField',
                                                    id: 'tfCantidadAtendida',
                                                    itemId: 'tfCantidadAtendida',
                                                    margin: '0 3 3 0',
                                                    fieldLabel: 'Atendidas',
                                                    labelWidth: 90,
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'splitter',
                                                    columnWidth: 1,
                                                    height: 0,
                                                    id: 'splitter1',
                                                    itemId: 'splitter1'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    columnWidth: 0.4,
                                                    disabled: true,
                                                    disabledCls: 'disabledField',
                                                    id: 'tfCantidadSaldo',
                                                    itemId: 'tfCantidadSaldo',
                                                    margin: '0 3 3 0',
                                                    fieldLabel: 'Saldo',
                                                    labelWidth: 90,
                                                    allowBlank: false
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'textareafield',
                                            columnWidth: 1,
                                            id: 'tfObservaciones',
                                            itemId: 'tfObservaciones',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Observaciones'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 470,
                            id: 'tabContacto',
                            itemId: 'tabContacto',
                            bodyCls: 'formBackground',
                            title: 'Contacto',
                            tabConfig: {
                                xtype: 'tab',
                                width: 130
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetInformacionVentas',
                                    itemId: 'fieldsetInformacionVentas',
                                    layout: 'column',
                                    title: '<b>Información de Ventas</b>',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxCodigoGerenteRegional',
                                            itemId: 'cbxCodigoGerenteRegional',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Gerente Regional',
                                            editable: false,
                                            autoLoadOnValue: true,
                                            displayField: 'nombre',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'storeCodigoGerenteRegional',
                                            valueField: 'usuario'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxCodigoVendedor',
                                            itemId: 'cbxCodigoVendedor',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Vendedor',
                                            editable: false,
                                            displayField: 'nombre',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'storeCodigoVendedor',
                                            valueField: 'usuario'
                                        },
                                        {
                                            xtype: 'combobox',
                                            columnWidth: 1,
                                            id: 'cbxCodigoConsecionario',
                                            itemId: 'cbxCodigoConsecionario',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Consecionario',
                                            editable: false,
                                            displayField: 'descripcion',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'storeCodigoConsecionario',
                                            valueField: 'codigo_consecionario'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetDatosContacto',
                                    itemId: 'fieldsetDatosContacto',
                                    layout: 'column',
                                    title: '<b>Datos Contacto</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            disabledCls: 'keyField',
                                            id: 'tfContactoNombre',
                                            itemId: 'tfContactoNombre',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Nombre',
                                            fieldCls: 'keyField',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            disabledCls: 'keyField',
                                            id: 'tfContactoCargo',
                                            itemId: 'tfContactoCargo',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Cargo',
                                            fieldCls: 'keyField',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabledCls: 'keyField',
                                            id: 'tfContactoTelefono',
                                            itemId: 'tfContactoTelefono',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Teléfono',
                                            fieldCls: 'keyField'
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            disabledCls: 'keyField',
                                            id: 'tfContactoMovil',
                                            itemId: 'tfContactoMovil',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Móvil',
                                            fieldCls: 'keyField',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 1,
                                            disabledCls: 'keyField',
                                            id: 'tfContactoEmail',
                                            itemId: 'tfContactoEmail',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Correo',
                                            fieldCls: 'keyField',
                                            allowBlank: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    id: 'fieldsetDatosUbicacion',
                                    itemId: 'fieldsetDatosUbicacion',
                                    layout: 'column',
                                    title: '<b>Ubicación</b>',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.94,
                                            id: 'tfSolicitudPais',
                                            itemId: 'tfSolicitudPais',
                                            margin: '0 0 3 0',
                                            fieldLabel: 'País',
                                            editable: false
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.03,
                                            cls: 'botonZoom',
                                            id: 'btnZoomPais',
                                            itemId: 'btnZoomPais',
                                            margin: '0 00 0 0',
                                            minWidth: 27,
                                            width: 27,
                                            iconCls: 'fa fa-search icon16 iconColorWhite',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnZoomPaisClick'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.94,
                                            id: 'tfSolicitudEstado',
                                            itemId: 'tfSolicitudEstado',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Estado',
                                            editable: false
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.03,
                                            cls: 'botonZoom',
                                            id: 'btnZoomEstado',
                                            itemId: 'btnZoomEstado',
                                            margin: '0 00 0 0',
                                            minWidth: 27,
                                            width: 27,
                                            iconCls: 'fa fa-search icon16 iconColorWhite',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnZoomEstadoClick'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.94,
                                            id: 'tfSolicitudMunicipio',
                                            itemId: 'tfSolicitudMunicipio',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Municipio',
                                            editable: false
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.03,
                                            cls: 'botonZoom',
                                            id: 'btnZoomMunicipio',
                                            itemId: 'btnZoomMunicipio',
                                            margin: '0 00 0 0',
                                            minWidth: 27,
                                            width: 27,
                                            iconCls: 'fa fa-search icon16 iconColorWhite',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnZoomMunicipioClick'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.94,
                                            id: 'tfSolicitudCiudad',
                                            itemId: 'tfSolicitudCiudad',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Colonia',
                                            editable: false
                                        },
                                        {
                                            xtype: 'button',
                                            columnWidth: 0.03,
                                            cls: 'botonZoom',
                                            id: 'btnZoomColonia',
                                            itemId: 'btnZoomColonia',
                                            margin: '0 00 0 0',
                                            minWidth: 27,
                                            width: 27,
                                            iconCls: 'fa fa-search icon16 iconColorWhite',
                                            textAlign: 'left',
                                            listeners: {
                                                click: 'onBtnZoomCiudadClick'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.5,
                                            id: 'tfSolicitudCp',
                                            itemId: 'tfSolicitudCp',
                                            margin: '0 3 3 0',
                                            fieldLabel: 'Codigo Postal'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 470,
                            id: 'tabCotizaciones',
                            itemId: 'tabCotizaciones',
                            bodyCls: 'formBackground',
                            title: 'Cotizaciones',
                            tabConfig: {
                                xtype: 'tab',
                                width: 130
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onBtnConfirmarOportunidadClick: function (button, e, eOpts) {
        Ext.getCmp('formOportunidadVenta').grabaOportunidadVenta();
    },

    onBtnCerrarOportunidadClick: function (button, e, eOpts) {
        elf.closeWindow('winOportunidadVenta');
    },

    onDtVisitaFechaChange: function (field, newValue, oldValue, eOpts) {
        var fechaActual = newValue;
        var annFecha = newValue.getFullYear();

        elf.writeElement('tfVisitaAnn', annFecha);
        elf.writeElement('tfVisitaSemana', elf.getWeekOfYear(fechaActual));
    },

    onCbxTipoSolicitanteChange: function (field, newValue, oldValue, eOpts) {
        switch (newValue) {
            case '1':
                elf.showElement('tfCodigoCliente');
                elf.showElement('btnZoomCliente');
                elf.disableElement('tfRazonSocial');
                break;
            case '2':
                elf.hideElement('tfCodigoCliente');
                elf.hideElement('btnZoomCliente');
                elf.enableElement('tfRazonSocial');
                break;
        }

    },

    onTfTipoEmpresaChange: function (field, newValue, oldValue, eOpts) {

    },

    onBtnZoomClienteClick: function (button, e, eOpts) {
        elf.openWindow('winBuscaCliente');
        elf.refreshGrid('gridBuscaCliente');
    },

    onTfCantidadSolicitadaChange: function (field, newValue, oldValue, eOpts) {
        var cantidadSolicitada = parseInt(elf.readElement('tfCantidadSolicitada'));
        var cantidadAtendida = parseInt(elf.readElement('tfCantidadAtendida'));
        var cantidadSaldo = parseInt(elf.readElement('tfCantidadSaldo'));

        cantidadSaldo = cantidadSolicitada - cantidadAtendida;

        if (!isNaN(cantidadSaldo)) {
            elf.writeElement('tfCantidadSaldo', cantidadSaldo);
        }
    },

    onBtnZoomPaisClick: function (button, e, eOpts) {
        elf.openWindow('winZoomGenerico');
        Ext.getCmp('winZoomGenerico').setTitle('Seleccione un Pais');

        var funcionSeleccionaRegistro = function () {
            registroActivo = Ext.getCmp('gridZoomGenerico').recordActivo;
            elf.writeElement('tfSolicitudPais', registroActivo.descripcion);
            elf.closeWindow('winZoomGenerico');
        };

        var funcionCarga = function () {
            var storeZoomGenerico = Ext.getStore('storeZoomGenerico');
            var proxyZoomGenerico = storeZoomGenerico.getProxy();

            var objJsonData = new Object();
            objJsonData.page = storeZoomGenerico.currentPage;
            objJsonData.start = (storeZoomGenerico.currentPage - 1) * storeZoomGenerico.pageSize;
            objJsonData.limit = storeZoomGenerico.pageSize;
            objJsonData.filtroEstado = 'ACTIVO';

            var objJsonRequest = new Object();
            objJsonRequest.apiController = 'sysApiLocalizacion';
            objJsonRequest.apiMethod = 'zoomPais';
            objJsonRequest.apiData = JSON.stringify(objJsonData);

            proxyZoomGenerico.api.read = elf.setApiDataBridge(objJsonRequest.apiController);
            proxyZoomGenerico.extraParams = objJsonRequest;

        };

        storeZoomGenerico = Ext.getStore('storeZoomGenerico');
        storeZoomGenerico.funcionCarga = funcionCarga;
        storeZoomGenerico.funcionSeleccionaRegistro = funcionSeleccionaRegistro;
        storeZoomGenerico.load();
    },

    onBtnZoomEstadoClick: function (button, e, eOpts) {
        elf.openWindow('winZoomGenerico');
        Ext.getCmp('winZoomGenerico').setTitle('Seleccione un Estado');

        var funcionSeleccionaRegistro = function () {
            registroActivo = Ext.getCmp('gridZoomGenerico').recordActivo;
            elf.writeElement('tfSolicitudEstado', registroActivo.descripcion);
            elf.writeElement('tfSolicitudMunicipio', '');
            elf.writeElement('tfSolicitudCiudad', '');
            elf.closeWindow('winZoomGenerico');
        };

        var funcionCarga = function () {
            console.log('funcion de carga');

            var storeZoomGenerico = Ext.getStore('storeZoomGenerico');
            var proxyZoomGenerico = storeZoomGenerico.getProxy();

            var objJsonData = new Object();
            objJsonData.page = storeZoomGenerico.currentPage;
            objJsonData.start = (storeZoomGenerico.currentPage - 1) * storeZoomGenerico.pageSize;
            objJsonData.limit = storeZoomGenerico.pageSize;
            objJsonData.filtroEstado = 'ACTIVO';
            objJsonData.pais = elf.readElement('tfSolicitudPais');

            var objJsonRequest = new Object();
            objJsonRequest.apiController = 'sysApiLocalizacion';
            objJsonRequest.apiMethod = 'zoomEstado';
            objJsonRequest.apiData = JSON.stringify(objJsonData);

            proxyZoomGenerico.api.read = elf.setApiDataBridge(objJsonRequest.apiController);
            proxyZoomGenerico.extraParams = objJsonRequest;

        };

        storeZoomGenerico = Ext.getStore('storeZoomGenerico');
        storeZoomGenerico.funcionCarga = funcionCarga;
        storeZoomGenerico.funcionSeleccionaRegistro = funcionSeleccionaRegistro;
        storeZoomGenerico.load();

    },

    onBtnZoomMunicipioClick: function (button, e, eOpts) {
        elf.openWindow('winZoomGenerico');
        Ext.getCmp('winZoomGenerico').setTitle('Seleccione un Estado');

        var funcionSeleccionaRegistro = function () {
            registroActivo = Ext.getCmp('gridZoomGenerico').recordActivo;
            elf.writeElement('tfSolicitudMunicipio', registroActivo.descripcion);
            elf.closeWindow('winZoomGenerico');
        };

        var funcionCarga = function () {
            console.log('funcion de carga');

            var storeZoomGenerico = Ext.getStore('storeZoomGenerico');
            var proxyZoomGenerico = storeZoomGenerico.getProxy();

            var objJsonData = new Object();
            objJsonData.page = storeZoomGenerico.currentPage;
            objJsonData.start = (storeZoomGenerico.currentPage - 1) * storeZoomGenerico.pageSize;
            objJsonData.limit = storeZoomGenerico.pageSize;
            objJsonData.filtroEstado = 'ACTIVO';
            objJsonData.pais = elf.readElement('tfSolicitudPais');
            objJsonData.estado = elf.readElement('tfSolicitudEstado');

            var objJsonRequest = new Object();
            objJsonRequest.apiController = 'sysApiLocalizacion';
            objJsonRequest.apiMethod = 'zoomMunicipio';
            objJsonRequest.apiData = JSON.stringify(objJsonData);

            proxyZoomGenerico.api.read = elf.setApiDataBridge(objJsonRequest.apiController);
            proxyZoomGenerico.extraParams = objJsonRequest;

        };

        storeZoomGenerico = Ext.getStore('storeZoomGenerico');
        storeZoomGenerico.funcionCarga = funcionCarga;
        storeZoomGenerico.funcionSeleccionaRegistro = funcionSeleccionaRegistro;
        storeZoomGenerico.load();
    },

    onBtnZoomCiudadClick: function (button, e, eOpts) {
        elf.openWindow('winZoomGenerico');
        Ext.getCmp('winZoomGenerico').setTitle('Seleccione un Estado');

        var funcionSeleccionaRegistro = function () {
            registroActivo = Ext.getCmp('gridZoomGenerico').recordActivo;
            elf.writeElement('tfSolicitudCiudad', registroActivo.descripcion);
            elf.closeWindow('winZoomGenerico');
        };

        var funcionCarga = function () {
            console.log('funcion de carga');

            var storeZoomGenerico = Ext.getStore('storeZoomGenerico');
            var proxyZoomGenerico = storeZoomGenerico.getProxy();

            var objJsonData = new Object();
            objJsonData.page = storeZoomGenerico.currentPage;
            objJsonData.start = (storeZoomGenerico.currentPage - 1) * storeZoomGenerico.pageSize;
            objJsonData.limit = storeZoomGenerico.pageSize;
            objJsonData.filtroEstado = 'ACTIVO';
            objJsonData.pais = elf.readElement('tfSolicitudPais');
            objJsonData.estado = elf.readElement('tfSolicitudEstado');
            objJsonData.municipio = elf.readElement('tfSolicitudMunicipio');

            var objJsonRequest = new Object();
            objJsonRequest.apiController = 'sysApiLocalizacion';
            objJsonRequest.apiMethod = 'zoomColonia';
            objJsonRequest.apiData = JSON.stringify(objJsonData);

            proxyZoomGenerico.api.read = elf.setApiDataBridge(objJsonRequest.apiController);
            proxyZoomGenerico.extraParams = objJsonRequest;

        };

        storeZoomGenerico = Ext.getStore('storeZoomGenerico');
        storeZoomGenerico.funcionCarga = funcionCarga;
        storeZoomGenerico.funcionSeleccionaRegistro = funcionSeleccionaRegistro;
        storeZoomGenerico.load();
    }

});