/*
 * File: app/view/winBuscaUnidadUsada.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProUnidades.view.winBuscaUnidadUsada', {
    extend: 'Ext.window.Window',
    alias: 'widget.winBuscaUnidadUsada',

    requires: [
        'hwtProUnidades.view.winBuscaUnidadUsadaViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'winbuscaunidadusada'
    },
    modal: true,
    id: 'winBuscaUnidadUsada',
    itemId: 'winBuscaUnidadUsada',
    width: 400,
    closable: false,
    title: 'Buscar Unidad Usada',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            cls: 'toolbarBackground',
            dock: 'bottom',
            items: [
                {
                    xtype: 'button',
                    id: 'btnConfirmaBuscaUnidadUsada',
                    itemId: 'btnConfirmaBuscaUnidadUsada',
                    width: 135,
                    iconCls: 'fa fa-check-square icon16 iconColorGreen',
                    text: 'Confirmar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnConfirmaUnidadUsadaClick'
                    }
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnCerrarBuscaUnidadUsada',
                    itemId: 'btnCerrarBuscaUnidadUsada',
                    width: 135,
                    iconCls: 'fa fa-window-close icon16 iconColorRed',
                    text: 'Cerrar',
                    textAlign: 'left',
                    listeners: {
                        click: 'onBtnCerrarBuscaUnidadUsadaClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            id: 'formBuscaUnidadUsada',
            itemId: 'formBuscaUnidadUsada',
            bodyCls: 'formBackground',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    id: 'tfBuscaCodigoUnidad',
                    itemId: 'tfBuscaCodigoUnidad',
                    width: 220,
                    fieldLabel: 'Código de Unidad',
                    labelWidth: 120
                }
            ]
        }
    ],

    onBtnConfirmaUnidadUsadaClick: function(button, e, eOpts) {
        var btnBuscarRegistro = Ext.getCmp('btnBuscarRegistro');

        btnBuscarRegistro.modoBusqueda = true;
        btnBuscarRegistro.formatoBoton();

    },

    onBtnCerrarBuscaUnidadUsadaClick: function(button, e, eOpts) {
        elf.closeWindow('winBuscaUnidadUsada');
    }

});