/*
 * File: app/view/winCargaMultiple.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hwtProUnidades.view.winCargaMultiple', {
    extend: 'Ext.window.Window',
    alias: 'widget.winCargaMultiple',

    requires: [
        'hwtProUnidades.view.winCargaMultipleViewModel',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'wincargamultiple'
    },
    id: 'winCargaMultiple',
    itemId: 'winCargaMultiple',
    width: 700,
    bodyCls: 'formBackground',
    closable: false,
    title: 'Carga Múltiple de Archivos',

    dockedItems: [
        {
            xtype: 'toolbar',
            baseCls: 'toolbarBackground',
            dock: 'top',
            id: 'toolbarCargaMultiple',
            itemId: 'toolbarCargaMultiple',
            items: [
                {
                    xtype: 'button',
                    width: 130,
                    iconCls: 'fa fa-cloud-upload icon16 iconColorBlue',
                    text: 'Cargar',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    width: 130,
                    iconCls: 'fa fa-trash icon16 iconColorRed',
                    text: 'Borrar Todo',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    width: 130,
                    iconCls: 'fa fa-trash-o icon16 iconColorDarkRed',
                    text: 'Borra Selección',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    width: 130,
                    iconCls: 'fa fa-window-close icon16 iconColorRed',
                    text: 'Cerrar',
                    textAlign: 'left'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'fieldset',
            margin: '0 5 5 5',
            layout: 'column',
            title: '<b>Registro de Unidad</b>',
            items: [
                {
                    xtype: 'textfield',
                    columnWidth: 0.5,
                    disabled: true,
                    disabledCls: 'disabledField',
                    id: 'tfCargaTipoUnidad',
                    itemId: 'tfCargaTipoUnidad',
                    margin: '0 5 5 5',
                    fieldLabel: 'Tipo'
                },
                {
                    xtype: 'textfield',
                    columnWidth: 0.5,
                    disabled: true,
                    disabledCls: 'disabledField',
                    id: 'tfCargaCodigoUnidad',
                    itemId: 'tfCargaCodigoUnidad',
                    margin: '0 5 5 5',
                    fieldLabel: 'Código'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            height: 400,
            id: 'gridArchivoCarga',
            itemId: 'gridArchivoCarga',
            title: 'Archivos para Carga',
            store: 'storeArchivoCarga',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Nombre'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'size',
                    text: 'Tamaño'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'file',
                    text: 'Archivo'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'status',
                    text: 'Status'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'alias',
                    text: 'Alias'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'storeArchivoCarga'
                }
            ]
        },
        {
            xtype: 'container',
            height: 80,
            id: 'containerDrag',
            itemId: 'containerDrag',
            liveDrag: true,
            layout: 'column',
            items: [
                {
                    xtype: 'label',
                    columnWidth: 1,
                    cls: 'fontAreaDragDrop',
                    id: 'lblCargaArchivos',
                    itemId: 'lblCargaArchivos',
                    margin: '30 100 0 100',
                    text: 'Arrastre los Archivos a ésta Area'
                }
            ]
        }
    ]

});