/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modPedidoVenta',
        'modPedidoVentaLinea',
        'modBuscaCliente',
        'modelBuscaVin',
        'modelFiltroMarca',
        'modelFiltroModelo',
        'modelFiltroSituacionPedido',
        'modCodigoGerenteRegional',
        'modCodigoVendedor',
        'modCodigoConsecionario',
        'modCodigoSucursal',
        'modCodigoConsecionarioEntrega',
        'modCodigoSucursalEntrega',
        'modPedidoVentaAdicional',
        'modProveedor',
        'modelFiltroTipoEntrega',
        'modBuscaGerenteRegional'
    ],
    stores: [
        'storePedidoVenta',
        'storePedidoVentaLinea',
        'storeBuscaCliente',
        'storeFiltroMarca',
        'storeBuscaVin',
        'storeFiltroModelo',
        'storeFiltroSituacionPedido',
        'storeCodigoGerenteRegional',
        'storeCodigoVendedor',
        'storeCodigoConsecionario',
        'storeCodigoSucursal',
        'storeCodigoConsecionarioEntrega',
        'storeCodigoSucursalEntrega',
        'storePedidoVentaAdicional',
        'storeProveedor',
        'storeFiltroTipoEntrega',
        'storeBuscaGerenteRegional'
    ],
    views: [
        'formAplicacion',
        'winPedidoVenta',
        'winBuscaCliente',
        'winBuscaVin',
        'winFactura',
        'winBuscaPedido'
    ],
    name: 'hwtProPedidoVentas',

    launch: function() {
        Ext.create('hwtProPedidoVentas.view.formAplicacion', {renderTo: Ext.getBody()});
        elf.defaultDataApp();

        appLocal = this.getApplication();
        Ext.EventManager.onWindowResize(function(w, h){
            appLocal.ajustarVentana();
        });

        appLocal.ajustarVentana();
        Ext.getCmp('formAplicacion').extraeOpcionesPedido();
        Ext.getCmp('formAplicacion').extraeListaProveedores();

        elf.refreshGrid('gridPedidoVenta');

    },

    ajustarVentana: function() {
        elf.renderInterface(
            'formAplicacion',
            'gridPedidoVenta',
            58);


        console.log('Ajustando el Render de l grid');
    }

});
